import type { PokerStats, VillainDef } from "./types";

function stats(partial: Partial<PokerStats> & Pick<PokerStats, "vpip" | "pfr" | "threeBet" | "foldToThreeBet" | "cbetFlop" | "foldToCbetFlop" | "turnBarrel" | "riverBluffFreq" | "wtsd" | "aggressionFactor" | "positionAwareness">): PokerStats {
  return {
    fourBet: 4,
    foldToFourBet: 55,
    cbetTurn: partial.turnBarrel,
    cbetRiver: Math.max(20, partial.riverBluffFreq + 18),
    foldToCbetTurn: Math.min(70, partial.foldToCbetFlop + 8),
    foldToCbetRiver: Math.min(75, partial.foldToCbetFlop + 14),
    checkRaiseFlop: 6,
    donkBetFreq: 4,
    showdownCalldownThreshold: 0.48,
    betSizingProfile: "standard",
    ...partial,
  };
}

export const VILLAINS: VillainDef[] = [
  {
    id: "professor",
    name: "교수",
    handle: "Professor_Kang",
    tier: "S",
    archetype: "밸런스드 / 근사 GTO",
    color: "#d8d2c4",
    accent: "#8a8376",
    mark: "교",
    talk: "극소",
    baseStats: stats({
      vpip: 24, pfr: 20, threeBet: 9, foldToThreeBet: 62, fourBet: 5, foldToFourBet: 52,
      cbetFlop: 62, foldToCbetFlop: 48, turnBarrel: 55, riverBluffFreq: 24,
      wtsd: 27, aggressionFactor: 2.8, positionAwareness: 1, showdownCalldownThreshold: 0.52,
    }),
    leaks: [{
      type: "STACK_MISREAD", magnitude: 0.04, condition: "40bb 이하",
      label: "숏스택 미세 오차",
      discoveryHint: "40bb 아래에서는 사이징이 한 박자 커집니다. 그 외엔 구멍 없습니다.",
      expectedEdge: 0,
    }],
    emotionProfile: { sensitivity: 0, tiltThreshold: 999, tiltDuration: 0, scaredThreshold: 999, confidentThreshold: 999 },
    adaptationLevel: 3,
    verbosity: 0.05,
    lines: {
      SESSION_START: ["시작하죠."],
      WIN_BIG: ["계산된 결과입니다."],
      LOSE_BIG: ["분산입니다."],
      BAD_BEAT: ["다음 핸드."],
      HERO_TANK: ["시간이 답을 바꾸진 않습니다."],
      STACK_LEAD: ["아직 의미 없습니다."],
    },
    unlock: "Tier A 3명 상대 누적 승률 플러스",
    lesson: "착취할 수 없는 상대와는 큰 팟을 만들지 않는다.",
    exploit: "본전 근처로 버티기. 돈을 뽑으려 하면 진다.",
    expectedBb100: "−1 ~ 0",
  },
  {
    id: "greatwhite",
    name: "백상어",
    handle: "GreatWhite",
    tier: "S",
    archetype: "프로급 LAG / 적응형",
    color: "#e8eef3",
    accent: "#6a7f8f",
    mark: "상",
    talk: "소",
    baseStats: stats({
      vpip: 30, pfr: 25, threeBet: 13, foldToThreeBet: 55, fourBet: 7,
      cbetFlop: 70, foldToCbetFlop: 42, turnBarrel: 62, riverBluffFreq: 31,
      wtsd: 29, aggressionFactor: 3.6, positionAwareness: 1, betSizingProfile: "large",
      showdownCalldownThreshold: 0.5,
    }),
    leaks: [{
      type: "FOLD_FREQ", magnitude: 0.035,
      label: "리버 블러프 과다",
      discoveryHint: "리버 블러프가 최적보다 조금 많습니다. 콜다운을 한 단계만 넓히세요.",
      expectedEdge: 3,
    }],
    emotionProfile: { sensitivity: 0, tiltThreshold: 999, tiltDuration: 0, scaredThreshold: 999, confidentThreshold: 80 },
    adaptationLevel: 3,
    adaptationRules: [
      { id: "punish-cbet-fold", when: "hero fold-to-cbet > 55%", effect: "c-bet 78%" },
      { id: "punish-3bet", when: "hero 3bet > 12%", effect: "4bet 빈도 2배" },
    ],
    verbosity: 0.1,
    lines: {
      SESSION_START: ["자리 좋네."],
      WIN_BIG: ["압박은 멈추지 않습니다."],
      STEAL_SUCCESS: ["그 블라인드, 내 겁니다."],
      HERO_BLUFF_SHOWN: ["한 번 더 해보세요. 기다리고 있을게요."],
      STACK_LEAD: ["이제부터가 본게임."],
    },
    unlock: "교수 상대 1,000핸드",
    lesson: "미세한 블러프 과다를 한 단계만 벌린다.",
    exploit: "리버 콜다운을 딱 한 단계 넓히기. 두 단계는 학살.",
    expectedBb100: "+2 ~ +4",
  },
  {
    id: "songtag",
    name: "송실장",
    handle: "SongTAG",
    tier: "A",
    archetype: "교과서 TAG",
    color: "#c9d4c4",
    accent: "#6d7d62",
    mark: "송",
    talk: "소",
    baseStats: stats({
      vpip: 22, pfr: 18, threeBet: 7, foldToThreeBet: 64, fourBet: 3, foldToFourBet: 78,
      cbetFlop: 68, foldToCbetFlop: 50, turnBarrel: 52, riverBluffFreq: 19,
      wtsd: 25, aggressionFactor: 2.6, positionAwareness: 0.85, showdownCalldownThreshold: 0.55,
    }),
    leaks: [{
      type: "RANGE", magnitude: 0.78,
      label: "4벳에 정직",
      discoveryHint: "4벳 레인지가 QQ+/AK로 고정입니다. fold to 4bet 78%.",
      expectedEdge: 8,
    }],
    emotionProfile: { sensitivity: 0.3, tiltThreshold: 55, tiltDuration: 8, scaredThreshold: 40, confidentThreshold: 70 },
    adaptationLevel: 2,
    verbosity: 0.12,
    lines: {
      SESSION_START: ["오늘도 기본에 충실하죠."],
      WIN_BIG: ["교과서대로입니다."],
      LOSE_BIG: ["괜찮은 플레이였습니다."],
      STEAL_SUCCESS: ["포지션이니까요."],
    },
    unlock: "중급 클리어",
    lesson: "정직한 3벳 팟은 라이트 4벳으로 연다.",
    exploit: "포지션에서 라이트 4벳. 송실장이 밀면 진짜다.",
    expectedBb100: "+8",
  },
  {
    id: "irongate",
    name: "철벽",
    handle: "IronGate",
    tier: "A",
    archetype: "포지션 극단 의존 TAG",
    color: "#b9c4d0",
    accent: "#5b6b7a",
    mark: "철",
    talk: "극소",
    baseStats: stats({
      vpip: 24, pfr: 20, threeBet: 8, foldToThreeBet: 60,
      cbetFlop: 71, foldToCbetFlop: 58, turnBarrel: 54, riverBluffFreq: 21,
      wtsd: 24, aggressionFactor: 2.7, positionAwareness: 0.95,
    }),
    positionalStats: {
      UTG: { vpip: 14, pfr: 13 },
      MP: { vpip: 18, pfr: 16 },
      CO: { vpip: 26, pfr: 22 },
      BTN: { vpip: 34, pfr: 30 },
      SB: { vpip: 20, pfr: 17 },
      BB: { vpip: 28, pfr: 8, foldToCbetFlop: 68 },
    },
    leaks: [{
      type: "POSITIONAL", magnitude: 0.68, condition: "OOP",
      label: "블라인드 플랍 과폴드",
      discoveryHint: "블라인드에서 콜한 뒤 플랍 c-bet에 68% 접습니다.",
      expectedEdge: 11,
    }],
    emotionProfile: { sensitivity: 0.4, tiltThreshold: 50, tiltDuration: 6, scaredThreshold: 35, confidentThreshold: 80 },
    adaptationLevel: 2,
    verbosity: 0.06,
    lines: {
      SESSION_START: ["…"],
      WIN_BIG: ["인포지션."],
      LOSE_BIG: ["아웃."],
    },
    unlock: "중급 클리어",
    lesson: "상대 스탯은 포지션별로 본다.",
    exploit: "블라인드 디펜스 후 플랍 c-bet은 거의 공짜. 버튼 오픈은 존중.",
    expectedBb100: "+11",
  },
  {
    id: "ceokim",
    name: "김대표",
    handle: "CEO_Kim",
    tier: "A",
    archetype: "오버벳 어그레시브 레귤러",
    color: "#e2c48a",
    accent: "#a67c2d",
    mark: "김",
    talk: "중",
    baseStats: stats({
      vpip: 26, pfr: 22, threeBet: 10, foldToThreeBet: 58,
      cbetFlop: 74, foldToCbetFlop: 46, turnBarrel: 60, riverBluffFreq: 22,
      wtsd: 26, aggressionFactor: 3.3, positionAwareness: 0.8, betSizingProfile: "overbet",
    }),
    leaks: [{
      type: "SIZING_TELL", magnitude: 0.14, condition: "리버 오버벳",
      label: "오버벳 = 강함",
      discoveryHint: "리버 팟 120% 오버벳의 블러프 비율은 14%입니다.",
      expectedEdge: 9,
    }],
    emotionProfile: { sensitivity: 0.7, tiltThreshold: 40, tiltDuration: 12, scaredThreshold: 45, confidentThreshold: 50 },
    adaptationLevel: 2,
    adaptationRules: [
      { id: "overbet-adjust", when: "hero fold to overbet 3회", effect: "블러프 32%로 25핸드" },
    ],
    verbosity: 0.25,
    lines: {
      SESSION_START: ["오늘은 크게 갑시다."],
      WIN_BIG: ["이 테이블, 내 페이스야."],
      LOSE_BIG: ["한 방이면 끝입니다."],
      STEAL_SUCCESS: ["사이즈가 곧 메시지죠."],
      HERO_TANK: ["생각할 거 없어요. 접으세요."],
    },
    unlock: "중급 클리어",
    lesson: "사이징이 정보를 샌다. 그리고 착취하면 카운터가 온다.",
    exploit: "리버 오버벳은 마진 핸드 전부 폴드. 팟 이하는 정상 콜.",
    expectedBb100: "+9 (적응 시 +6)",
  },
  {
    id: "nitlee",
    name: "이대리",
    handle: "Nit_Lee",
    tier: "B",
    archetype: "클래식 닛",
    color: "#cfc8d8",
    accent: "#6f6580",
    mark: "이",
    talk: "극소",
    baseStats: stats({
      vpip: 15, pfr: 12, threeBet: 4, foldToThreeBet: 82, fourBet: 2, foldToFourBet: 70,
      cbetFlop: 65, foldToCbetFlop: 55, turnBarrel: 45, riverBluffFreq: 9,
      wtsd: 22, aggressionFactor: 2.0, positionAwareness: 0.55, showdownCalldownThreshold: 0.66,
    }),
    leaks: [{
      type: "RANGE", magnitude: 0.82,
      label: "3벳에 접는다",
      discoveryHint: "VPIP 15, fold to 3bet 82%. 오픈하면 진짜고 3벳하면 거의 팟을 줍니다.",
      expectedEdge: 16,
    }],
    emotionProfile: { sensitivity: 0.5, tiltThreshold: 45, tiltDuration: 8, scaredThreshold: 20, confidentThreshold: 90 },
    adaptationLevel: 1,
    verbosity: 0.08,
    lines: {
      SESSION_START: ["오늘은 조심해서…"],
      WIN_BIG: ["기다려서 된 겁니다."],
      LOSE_BIG: ["이런."],
      HERO_BLUFF_SHOWN: ["저는 그런 거 잘 못 해요."],
    },
    unlock: "즉시",
    lesson: "닛의 오픈은 접고, 블라인드는 훔친다.",
    exploit: "3벳으로 팟을 가져가라. 되받으면 무조건 진짜다.",
    expectedBb100: "+16",
  },
  {
    id: "stationpark",
    name: "박사장",
    handle: "StationPark",
    tier: "B",
    archetype: "콜링 스테이션",
    color: "#e0b089",
    accent: "#a86a38",
    mark: "박",
    talk: "중",
    baseStats: stats({
      vpip: 34, pfr: 12, threeBet: 2, foldToThreeBet: 48,
      cbetFlop: 38, foldToCbetFlop: 22, turnBarrel: 30, riverBluffFreq: 7,
      foldToCbetRiver: 12, wtsd: 41, aggressionFactor: 0.9, positionAwareness: 0.35,
      showdownCalldownThreshold: 0.22, betSizingProfile: "large",
    }),
    leaks: [{
      type: "FOLD_FREQ", magnitude: 0.12,
      label: "리버에 안 접음",
      discoveryHint: "fold to river bet 12%, WTSD 41%. 블러프는 성립하지 않습니다.",
      expectedEdge: 22,
    }],
    emotionProfile: { sensitivity: 0.6, tiltThreshold: 50, tiltDuration: 10, scaredThreshold: 50, confidentThreshold: 40 },
    adaptationLevel: 1,
    verbosity: 0.28,
    lines: {
      SESSION_START: ["오늘 느낌 좋은데?"],
      WIN_BIG: ["봐, 콜하니까 이기잖아."],
      LOSE_BIG: ["에이 한 장 차이네."],
      HERO_BLUFF_SHOWN: ["그럴 줄 알았으면 콜하지. 다음엔 콜한다."],
      STEAL_SUCCESS: ["이건 좀 치사한 거 아니야?"],
    },
    unlock: "즉시",
    lesson: "안 접는 상대에게 블러프는 기부다.",
    exploit: "블러프 금지. 세컨페어로도 크게 밸류.",
    expectedBb100: "+22",
  },
  {
    id: "madamj",
    name: "여사장",
    handle: "Madam_J",
    tier: "B",
    archetype: "포지션 어웨어 LAG",
    color: "#e3b7c6",
    accent: "#a45d76",
    mark: "여",
    talk: "다",
    baseStats: stats({
      vpip: 32, pfr: 27, threeBet: 12, foldToThreeBet: 65,
      cbetFlop: 76, foldToCbetFlop: 44, turnBarrel: 58, riverBluffFreq: 28,
      wtsd: 26, aggressionFactor: 3.4, positionAwareness: 0.95, betSizingProfile: "large",
    }),
    positionalStats: {
      UTG: { vpip: 12, pfr: 11 },
      MP: { vpip: 18, pfr: 16 },
      CO: { vpip: 38, pfr: 33 },
      BTN: { vpip: 52, pfr: 47, foldToThreeBet: 65 },
      SB: { vpip: 30, pfr: 26 },
      BB: { vpip: 34, pfr: 9 },
    },
    leaks: [{
      type: "POSITIONAL", magnitude: 0.65, condition: "BTN",
      label: "버튼 스틸 과다",
      discoveryHint: "버튼 VPIP 52%인데 3벳에 65% 접습니다. 스틸이 뻔합니다.",
      expectedEdge: 13,
    }],
    emotionProfile: { sensitivity: 0.8, tiltThreshold: 35, tiltDuration: 14, scaredThreshold: 40, confidentThreshold: 40 },
    adaptationLevel: 2,
    verbosity: 0.38,
    lines: {
      SESSION_START: ["오늘 누가 밥이야?"],
      WIN_BIG: ["버튼은 내 자리거든."],
      LOSE_BIG: ["재밌네. 한 번 더."],
      STEAL_SUCCESS: ["거저네, 거저."],
      HERO_TANK: ["오래 생각한다고 핸드가 좋아지진 않아."],
      HERO_BLUFF_SHOWN: ["그거 나한테만 해. 다른 데선 죽어."],
    },
    unlock: "기초 클리어",
    lesson: "포지션이 사람을 바꾼다.",
    exploit: "블라인드에서 버튼 오픈에 라이트 3벳.",
    expectedBb100: "+13",
  },
  {
    id: "bulldozer",
    name: "불도저",
    handle: "Bulldozer",
    tier: "B",
    archetype: "브레이크 있는 매니악",
    color: "#d9896a",
    accent: "#9a3f24",
    mark: "불",
    talk: "다",
    baseStats: stats({
      vpip: 48, pfr: 36, threeBet: 16, foldToThreeBet: 44,
      cbetFlop: 82, foldToCbetFlop: 38, turnBarrel: 38, riverBluffFreq: 26,
      wtsd: 32, aggressionFactor: 3.1, positionAwareness: 0.45, betSizingProfile: "large",
    }),
    leaks: [{
      type: "STREET_GAP", magnitude: 0.44,
      label: "턴에서 멈춘다",
      discoveryHint: "플랍 c-bet 82% → 턴 배럴 38%. 플랍 압박은 대부분 허세입니다.",
      expectedEdge: 19,
    }],
    emotionProfile: { sensitivity: 1.6, tiltThreshold: 22, tiltDuration: 18, scaredThreshold: 50, confidentThreshold: 30 },
    adaptationLevel: 1,
    verbosity: 0.35,
    lines: {
      SESSION_START: ["자 밀자 밀자!"],
      WIN_BIG: ["이게 포커지!"],
      LOSE_BIG: ["아오 진짜!!"],
      TILT_ENTER: ["오늘은 다 가져간다."],
      STEAL_SUCCESS: ["겁먹지 마 겁먹지 마."],
      HERO_TANK: ["빨리 안 해? 접을 거면서."],
    },
    unlock: "200핸드",
    lesson: "스트리트 간 공격성 단절을 읽는다.",
    exploit: "플랍은 콜, 턴에서 뺏어와라.",
    expectedBb100: "+19",
  },
  {
    id: "foldjeong",
    name: "정과장",
    handle: "FoldJeong",
    tier: "B",
    archetype: "사이징 민감 오버폴더",
    color: "#b7c7b2",
    accent: "#5f7358",
    mark: "정",
    talk: "극소",
    baseStats: stats({
      vpip: 20, pfr: 16, threeBet: 6, foldToThreeBet: 70,
      cbetFlop: 64, foldToCbetFlop: 61, turnBarrel: 48, riverBluffFreq: 14,
      wtsd: 19, aggressionFactor: 2.2, positionAwareness: 0.6, showdownCalldownThreshold: 0.6,
    }),
    leaks: [{
      type: "SIZING_TELL", magnitude: 0.71, condition: "리버 큰 벳",
      label: "큰 벳에 접는다",
      discoveryHint: "리버 팟 75%+ 벳에 71% 폴드, 40% 이하엔 18%만 폴드합니다.",
      expectedEdge: 14,
    }],
    emotionProfile: { sensitivity: 0.4, tiltThreshold: 50, tiltDuration: 6, scaredThreshold: 28, confidentThreshold: 80 },
    adaptationLevel: 1,
    verbosity: 0.08,
    lines: {
      SESSION_START: ["무리하지 맙시다."],
      WIN_BIG: ["이 정도면 충분하죠."],
      LOSE_BIG: ["너무 컸어요."],
    },
    unlock: "200핸드",
    lesson: "상대에 따라 사이징 원칙이 뒤집힌다.",
    exploit: "블러프는 크게, 밸류는 작게.",
    expectedBb100: "+14",
  },
  {
    id: "uncleho",
    name: "삼촌",
    handle: "Uncle_Ho",
    tier: "C",
    archetype: "루즈 패시브 림퍼",
    color: "#d2c09a",
    accent: "#8a7040",
    mark: "삼",
    talk: "다",
    baseStats: stats({
      vpip: 42, pfr: 9, threeBet: 2, foldToThreeBet: 55,
      cbetFlop: 44, foldToCbetFlop: 63, turnBarrel: 28, riverBluffFreq: 8,
      wtsd: 30, aggressionFactor: 1.1, positionAwareness: 0.25, donkBetFreq: 12,
      showdownCalldownThreshold: 0.4, betSizingProfile: "small",
    }),
    leaks: [{
      type: "FOLD_FREQ", magnitude: 0.63,
      label: "핏 오어 폴드",
      discoveryHint: "림프를 사랑하고, 플랍 c-bet에 63% 접습니다. 레이즈하면 진짜입니다.",
      expectedEdge: 20,
    }],
    emotionProfile: { sensitivity: 0.9, tiltThreshold: 35, tiltDuration: 12, scaredThreshold: 30, confidentThreshold: 45 },
    adaptationLevel: 1,
    verbosity: 0.4,
    lines: {
      SESSION_START: ["아이고 오늘 한잔한 것치고는 괜찮네."],
      WIN_BIG: ["삼촌 카드 한번 받으니까 이래."],
      LOSE_BIG: ["에이 그럴 수도 있지 뭐."],
      STEAL_SUCCESS: ["젊은 사람들이 너무 빨라."],
      LONG_FOLD: ["나 또 림프하게 생겼어."],
      HERO_TANK: ["뭘 그렇게 오래 생각해. 콜이든 폴드든 해."],
    },
    unlock: "즉시",
    lesson: "림퍼는 아이솔레이션 후 c-bet.",
    exploit: "림프 뒤에 레이즈하고 플랍을 베팅하라.",
    expectedBb100: "+20",
  },
  {
    id: "tourneymin",
    name: "토너꾼",
    handle: "Tourney_Min",
    tier: "C",
    archetype: "토너먼트 출신, 캐시 부적응",
    color: "#9eb8d4",
    accent: "#3f6790",
    mark: "토",
    talk: "중",
    baseStats: stats({
      vpip: 25, pfr: 21, threeBet: 11, foldToThreeBet: 56,
      cbetFlop: 72, foldToCbetFlop: 47, turnBarrel: 56, riverBluffFreq: 20,
      wtsd: 28, aggressionFactor: 3.0, positionAwareness: 0.75, showdownCalldownThreshold: 0.38,
    }),
    leaks: [{
      type: "STACK_MISREAD", magnitude: 0.4,
      label: "탑페어 스택오프",
      discoveryHint: "100bb를 40bb처럼 칩니다. 탑페어면 스택을 넣습니다.",
      expectedEdge: 12,
    }],
    emotionProfile: { sensitivity: 0.7, tiltThreshold: 40, tiltDuration: 10, scaredThreshold: 45, confidentThreshold: 50 },
    adaptationLevel: 1,
    verbosity: 0.22,
    lines: {
      SESSION_START: ["ICM은 없어도 압박은 있습니다."],
      WIN_BIG: ["커밋이죠."],
      LOSE_BIG: ["토너였으면 끝난 핸드인데."],
      STACK_LEAD: ["칩 리더 페이스 유지합니다."],
    },
    unlock: "기초 클리어",
    lesson: "SPR과 커밋 임계값.",
    exploit: "강한 핸드로 스택을 노려라. 마진 핸드로 큰 팟을 만들지 마라.",
    expectedBb100: "+12",
  },
  {
    id: "vendetta",
    name: "복수의화신",
    handle: "Vendetta",
    tier: "C",
    archetype: "틸트 폭발형",
    color: "#d97a7a",
    accent: "#8d2d2d",
    mark: "복",
    talk: "가변",
    baseStats: stats({
      vpip: 24, pfr: 19, threeBet: 8, foldToThreeBet: 62,
      cbetFlop: 67, foldToCbetFlop: 49, turnBarrel: 51, riverBluffFreq: 18,
      wtsd: 26, aggressionFactor: 2.5, positionAwareness: 0.7,
    }),
    leaks: [{
      type: "EMOTIONAL", magnitude: 2.0,
      label: "틸트 폭발",
      discoveryHint: "큰 팟을 잃거나 블러프에 당하면 30핸드 동안 사람이 바뀝니다.",
      expectedEdge: 17,
    }],
    emotionProfile: { sensitivity: 2.0, tiltThreshold: 20, tiltDuration: 30, scaredThreshold: 50, confidentThreshold: 55 },
    adaptationLevel: 1,
    verbosity: 0.15,
    lines: {
      SESSION_START: ["오늘은 조용히 치죠."],
      WIN_BIG: ["이 정도는 기본이고."],
      LOSE_BIG: ["…"],
      TILT_ENTER: ["좋아. 이제 진짜로 한다."],
      HERO_BLUFF_SHOWN: ["그거 보여준 거, 후회하게 해줄게."],
      BAD_BEAT: ["운으로 이긴 거 알지?"],
    },
    unlock: "기초 클리어",
    lesson: "상대의 심리 상태가 스탯보다 중요할 때가 있다.",
    exploit: "큰 팟을 이긴 뒤 블러프를 보여주면 이후 30핸드는 ATM.",
    expectedBb100: "+17",
  },
  {
    id: "slowroll",
    name: "슬로우롤",
    handle: "SlowRoll_Cha",
    tier: "C",
    archetype: "타이밍 텔 보유자",
    color: "#c4b7a2",
    accent: "#7a6a50",
    mark: "슬",
    talk: "중",
    baseStats: stats({
      vpip: 26, pfr: 19, threeBet: 7, foldToThreeBet: 61,
      cbetFlop: 66, foldToCbetFlop: 52, turnBarrel: 50, riverBluffFreq: 17,
      wtsd: 27, aggressionFactor: 2.4, positionAwareness: 0.65,
    }),
    leaks: [{
      type: "PHYSICAL", magnitude: 0.78,
      label: "액션 속도 텔",
      discoveryHint: "강한 핸드 1.2초, 블러프 4.8초. 다만 22%는 역텔입니다.",
      expectedEdge: 15,
    }],
    emotionProfile: { sensitivity: 0.6, tiltThreshold: 45, tiltDuration: 10, scaredThreshold: 40, confidentThreshold: 55 },
    adaptationLevel: 1,
    verbosity: 0.22,
    timingTell: true,
    lines: {
      SESSION_START: ["오늘은 천천히 가볼까."],
      WIN_BIG: ["급할 거 하나도 없거든."],
      LOSE_BIG: ["성급했나."],
      HERO_TANK: ["나도 가끔 그렇게 오래 생각해. 보통은 허세일 때."],
    },
    unlock: "기초 클리어",
    lesson: "숫자 밖의 정보, 그리고 78%짜리 정보를 어떻게 쓸 것인가.",
    exploit: "빠른 액션은 강함, 느린 액션은 블러프. 맹신하면 역텔에 당한다.",
    expectedBb100: "+15",
  },
  {
    id: "weekend",
    name: "주말전사",
    handle: "Weekend_Kwon",
    tier: "C",
    archetype: "스캐어드 머니",
    color: "#b8c9c2",
    accent: "#4f7268",
    mark: "주",
    talk: "소",
    baseStats: stats({
      vpip: 18, pfr: 14, threeBet: 5, foldToThreeBet: 72,
      cbetFlop: 60, foldToCbetFlop: 57, turnBarrel: 42, riverBluffFreq: 11,
      wtsd: 21, aggressionFactor: 1.9, positionAwareness: 0.6, showdownCalldownThreshold: 0.58,
    }),
    leaks: [{
      type: "STACK_MISREAD", magnitude: 0.35, condition: "팟 60bb+",
      label: "큰 팟에서 위축",
      discoveryHint: "팟이 60bb를 넘는 순간 폴드 빈도가 크게 올라갑니다.",
      expectedEdge: 16,
    }],
    emotionProfile: { sensitivity: 1.2, tiltThreshold: 40, tiltDuration: 8, scaredThreshold: 25, confidentThreshold: 90 },
    adaptationLevel: 1,
    verbosity: 0.12,
    lines: {
      SESSION_START: ["너무 큰 테이블은 아니죠?"],
      WIN_BIG: ["이 정도면 오늘은 충분해요."],
      LOSE_BIG: ["집사람이 알면 안 되는데…"],
      SCARED_ENTER: ["이건 좀 큰데요."],
    },
    unlock: "200핸드",
    lesson: "팟 사이즈 자체가 상대를 바꾸는 레버다.",
    exploit: "사이징을 키워 팟을 60bb 위로 올리면 그 다음은 폴드.",
    expectedBb100: "+16",
  },
];

export const VILLAIN_BY_ID: Record<string, VillainDef> = Object.fromEntries(
  VILLAINS.map((v) => [v.id, v]),
);

export const PRESETS = [
  {
    id: "intro",
    name: "입문",
    stars: 1,
    goal: "기본 착취 패턴",
    villains: ["uncleho", "stationpark", "nitlee", "foldjeong", "weekend"],
  },
  {
    id: "regular",
    name: "레귤러",
    stars: 3,
    goal: "포지션·스탯 읽기",
    villains: ["songtag", "irongate", "madamj", "tourneymin", "bulldozer"],
  },
  {
    id: "chaos",
    name: "카오스",
    stars: 3,
    goal: "분산 관리, 감정 활용",
    villains: ["bulldozer", "madamj", "vendetta", "stationpark", "slowroll"],
  },
  {
    id: "observe",
    name: "관찰 훈련",
    stars: 4,
    goal: "상황 의존 leak 탐지",
    villains: ["slowroll", "vendetta", "weekend", "irongate", "ceokim"],
  },
  {
    id: "sharks",
    name: "상어 수조",
    stars: 5,
    goal: "버티기, 테이블 셀렉션",
    villains: ["professor", "greatwhite", "songtag", "ceokim", "irongate"],
  },
] as const;

export const TUTORIAL_VILLAINS = ["uncleho", "nitlee", "stationpark"];
export const STARTER_UNLOCKS = ["uncleho", "nitlee", "stationpark"];
