import type { TriggerType } from "./types";

export const DIALOGUE: Record<string, Partial<Record<TriggerType, string[]>>> = {
  professor: {
    SESSION_START: ["시작하죠.", "준비됐으면 됩니다."],
    WIN_BIG: ["계산된 결과입니다.", "분산을 이긴 것뿐입니다."],
    LOSE_BIG: ["분산입니다.", "다음 핸드."],
    BAD_BEAT: ["다음 핸드.", "확률은 변하지 않습니다."],
    HERO_TANK: ["시간이 답을 바꾸진 않습니다."],
    STACK_LEAD: ["아직 의미 없습니다."],
    BLUFF_SHOWN: ["블러프 빈도는 유지합니다."],
    HERO_BLUFF_SHOWN: ["기록했습니다."],
  },
  greatwhite: {
    SESSION_START: ["자리 좋네.", "압박은 제가 할게요."],
    WIN_BIG: ["압박은 멈추지 않습니다.", "이게 페이스입니다."],
    LOSE_BIG: ["한 방으로는 안 끝납니다.", "다시."],
    STEAL_SUCCESS: ["그 블라인드, 내 겁니다.", "포지션은 공짜가 아닙니다."],
    HERO_BLUFF_SHOWN: ["한 번 더 해보세요. 기다리고 있을게요.", "폴드 빈도, 잘 봤습니다."],
    STACK_LEAD: ["이제부터가 본게임.", "칩은 도구입니다."],
    HERO_TANK: ["접을 거면 접으세요."],
    BAD_BEAT: ["운은 한 핸드입니다."],
  },
  songtag: {
    SESSION_START: ["오늘도 기본에 충실하죠.", "교과서대로 가겠습니다."],
    WIN_BIG: ["교과서대로입니다.", "레인지가 맞았습니다."],
    LOSE_BIG: ["괜찮은 플레이였습니다.", "결과는 결과고요."],
    STEAL_SUCCESS: ["포지션이니까요."],
    HERO_TANK: ["기본부터 보면 답이 나옵니다."],
    BLUFF_SHOWN: ["드물게 하는 겁니다."],
    LONG_FOLD: ["카드가 안 오면 기다리는 거죠."],
  },
  irongate: {
    SESSION_START: ["…", "시작."],
    WIN_BIG: ["인포지션.", "버튼."],
    LOSE_BIG: ["아웃.", "블라인드."],
    STEAL_SUCCESS: ["버튼."],
    BAD_BEAT: ["…"],
    STACK_LEAD: ["유지."],
  },
  ceokim: {
    SESSION_START: ["오늘은 크게 갑시다.", "사이즈가 곧 메시지죠."],
    WIN_BIG: ["이 테이블, 내 페이스야.", "크게 가야 크게 먹죠."],
    LOSE_BIG: ["한 방이면 끝입니다.", "다음엔 더 크게."],
    STEAL_SUCCESS: ["사이즈가 곧 메시지죠.", "작게 내는 사람은 작게 먹어요."],
    HERO_TANK: ["생각할 거 없어요. 접으세요.", "오버벳 앞에 마진은 없어요."],
    HERO_BLUFF_SHOWN: ["그 사이즈로 블러프? 용기 있네.", "다음엔 더 크게 갈게요."],
    STACK_LEAD: ["이제 진짜 게임이지."],
    BAD_BEAT: ["운도 사이즈로 덮습니다."],
    BLUFF_SHOWN: ["가끔은 크게 밀어야죠."],
  },
  nitlee: {
    SESSION_START: ["오늘은 조심해서…", "무리하지 않을게요."],
    WIN_BIG: ["기다려서 된 겁니다.", "올 때까지 기다렸죠."],
    LOSE_BIG: ["이런.", "제가 낸 핸드였는데요."],
    HERO_BLUFF_SHOWN: ["저는 그런 거 잘 못 해요.", "그런 플레이는… 어려워요."],
    STEAL_SUCCESS: ["블라인드는… 네."],
    LONG_FOLD: ["카드가 없네요.", "또 접는 수밖에."],
    HERO_TANK: ["저는 빨리 접는 편이에요."],
    BAD_BEAT: ["아… 진짜였는데요."],
  },
  stationpark: {
    SESSION_START: ["오늘 느낌 좋은데?", "콜할 맛 나는 날이야."],
    WIN_BIG: ["봐, 콜하니까 이기잖아.", "페어면 가는 거지."],
    LOSE_BIG: ["에이 한 장 차이네.", "다음엔 맞겠지."],
    HERO_BLUFF_SHOWN: ["그럴 줄 알았으면 콜하지. 다음엔 콜한다.", "블러프였어? 야 이거 열받네."],
    STEAL_SUCCESS: ["이건 좀 치사한 거 아니야?", "블라인드는 내 건데."],
    LONG_FOLD: ["나 왜 이렇게 카드를 안 주지.", "조금만 맞으면 가는데."],
    HERO_TANK: ["고민하지 마. 콜이야.", "탑페어면 가는 거야."],
    BAD_BEAT: ["내가 이기고 있었는데!", "리버가 왜 이래."],
    BLUFF_SHOWN: ["나도 가끔은… 아니 그냥 맞았음."],
    TILT_ENTER: ["오늘은 다 콜한다."],
    STACK_LEAD: ["콜의 힘이지."],
  },
  madamj: {
    SESSION_START: ["오늘 누가 밥이야?", "버튼은 내 자리거든."],
    WIN_BIG: ["버튼은 내 자리거든.", "거저네, 거저."],
    LOSE_BIG: ["재밌네. 한 번 더.", "아직 안 끝났어."],
    STEAL_SUCCESS: ["거저네, 거저.", "블라인드 수비 그거밖에 안 돼?"],
    HERO_TANK: ["오래 생각한다고 핸드가 좋아지진 않아.", "접을 얼굴인데."],
    HERO_BLUFF_SHOWN: ["그거 나한테만 해. 다른 데선 죽어.", "귀엽네."],
    BAD_BEAT: ["운으로 이긴 거 알지?", "한 장 차이로 기세 잡지 마."],
    TILT_ENTER: ["좋아, 이제 진짜로 할게."],
    STACK_LEAD: ["이 테이블 분위기 좋지?"],
    LONG_FOLD: ["너 오늘 카드 없니?"],
    BLUFF_SHOWN: ["가끔은 밀어야 예의가 되지."],
  },
  bulldozer: {
    SESSION_START: ["자 밀자 밀자!", "브레이크는 나중에!"],
    WIN_BIG: ["이게 포커지!", "밀면 이겨!"],
    LOSE_BIG: ["아오 진짜!!", "한 번 더 밀어!"],
    TILT_ENTER: ["오늘은 다 가져간다.", "이제 진짜 미친다."],
    STEAL_SUCCESS: ["겁먹지 마 겁먹지 마.", "블라인드 내놔!"],
    HERO_TANK: ["빨리 안 해? 접을 거면서.", "고민은 폴드야!"],
    BAD_BEAT: ["아오 리버!!", "이게 말이 돼?"],
    HERO_BLUFF_SHOWN: ["야 그거 보여줬어? 좋아 더 밀어.", "열받네 진짜."],
    LONG_FOLD: ["너 오늘 숨쉬냐?", "카드 없어도 밀 수 있어!"],
    STACK_LEAD: ["칩 많으면 더 밀어!", "자 더!"],
    BLUFF_SHOWN: ["허세? 이게 허세지!"],
    SCARED_ENTER: ["잠깐만… 아니 밀어."],
  },
  foldjeong: {
    SESSION_START: ["무리하지 맙시다.", "작게 가죠."],
    WIN_BIG: ["이 정도면 충분하죠.", "크게 안 내도 됩니다."],
    LOSE_BIG: ["너무 컸어요.", "사이즈가 문제였습니다."],
    HERO_TANK: ["크게 내면 접을게요.", "작은 건 콜합니다."],
    STEAL_SUCCESS: ["작은 거였으니까요."],
    LONG_FOLD: ["오늘은 핸드가 안 오네요."],
    BAD_BEAT: ["크게 낸 게 아니었는데요."],
    SCARED_ENTER: ["이건 너무 큽니다."],
  },
  uncleho: {
    SESSION_START: ["아이고 오늘 한잔한 것치고는 괜찮네.", "삼촌도 한자리 하지 뭐."],
    WIN_BIG: ["삼촌 카드 한번 받으니까 이래.", "보면 가는 거야."],
    LOSE_BIG: ["에이 그럴 수도 있지 뭐.", "다음 핸드 있지."],
    STEAL_SUCCESS: ["젊은 사람들이 너무 빨라.", "블라인드는 좀 남겨두지."],
    LONG_FOLD: ["나 또 림프하게 생겼어.", "카드가 왜 이래 진짜."],
    HERO_TANK: ["뭘 그렇게 오래 생각해. 콜이든 폴드든 해.", "아이고 답답해."],
    BAD_BEAT: ["에이 마지막 장이 왜 그래.", "삼촌 운도 없네."],
    HERO_BLUFF_SHOWN: ["야 그게 허세였어? 나 진짜인 줄.", "젊은 사람 무섭네."],
    TILT_ENTER: ["오늘은 그냥 다 보지 뭐."],
    STACK_LEAD: ["아이고 내가 제일 많아?", "한잔 더 해야겠네."],
    BLUFF_SHOWN: ["나도 허세 한번 해봤어.", "그냥 나온 거야."],
    SCARED_ENTER: ["이건 좀 큰데… 아이고."],
  },
  tourneymin: {
    SESSION_START: ["ICM은 없어도 압박은 있습니다.", "캐시라도 토너처럼 칩니다."],
    WIN_BIG: ["커밋이죠.", "탑페어면 넣는 겁니다."],
    LOSE_BIG: ["토너였으면 끝난 핸드인데.", "스택오프가 맞았어요."],
    STACK_LEAD: ["칩 리더 페이스 유지합니다.", "압박을 풀면 안 됩니다."],
    HERO_TANK: ["SPR 계산하세요. 이미 늦었을 수도."],
    STEAL_SUCCESS: ["스틸도 토너 감각이죠."],
    BAD_BEAT: ["버블이었으면 접었을 핸드인데."],
    BLUFF_SHOWN: ["숏스택 감각이 남았습니다."],
  },
  vendetta: {
    SESSION_START: ["오늘은 조용히 치죠.", "감정은 넣지 않겠습니다."],
    WIN_BIG: ["이 정도는 기본이고.", "담담하게."],
    LOSE_BIG: ["…", "기억합니다."],
    TILT_ENTER: ["좋아. 이제 진짜로 한다.", "그 핸드, 값 치르게 해줄게.", "참는 것도 한계가 있어."],
    HERO_BLUFF_SHOWN: ["그거 보여준 거, 후회하게 해줄게.", "허세를 보여? 좋아."],
    BAD_BEAT: ["운으로 이긴 거 알지?", "그 리버, 잊지 마."],
    STEAL_SUCCESS: ["이건 그냥 가져가는 거야."],
    LONG_FOLD: ["카드 없어도 사람은 남죠."],
    STACK_LEAD: ["이제 내가 위에 있어."],
    BLUFF_SHOWN: ["평소엔 안 해. 지금은 한다."],
    SCARED_ENTER: ["아니, 겁먹은 거 아니야."],
    HERO_TANK: ["오래 생각하네. 죄책감인가."],
  },
  slowroll: {
    SESSION_START: ["오늘은 천천히 가볼까.", "급할 거 하나도 없거든."],
    WIN_BIG: ["급할 거 하나도 없거든.", "천천히 이기면 돼."],
    LOSE_BIG: ["성급했나.", "조금 빨랐나 보네."],
    HERO_TANK: ["나도 가끔 그렇게 오래 생각해. 보통은 허세일 때.", "시간은 정보야."],
    STEAL_SUCCESS: ["천천히 가져갈게."],
    BAD_BEAT: ["서두르지 말걸."],
    BLUFF_SHOWN: ["오래 생각한 티 났나."],
    HERO_BLUFF_SHOWN: ["빠르게 냈지? 아니면 느리게?", "타이밍, 재밌네."],
    LONG_FOLD: ["기다리면 또 오거든."],
    STACK_LEAD: ["천천히 쌓이는 맛이지."],
  },
  weekend: {
    SESSION_START: ["너무 큰 테이블은 아니죠?", "주말만 치는 거라서요."],
    WIN_BIG: ["이 정도면 오늘은 충분해요.", "여기서 그만해도…"],
    LOSE_BIG: ["집사람이 알면 안 되는데…", "오늘 한도 넘은 것 같아요."],
    SCARED_ENTER: ["이건 좀 큰데요.", "팟이 너무 커요."],
    HERO_TANK: ["크게 내면 저 접을 수도 있어요."],
    STEAL_SUCCESS: ["작은 팟은 괜찮죠."],
    BAD_BEAT: ["큰돈 잃으면 진짜 힘들어요."],
    LONG_FOLD: ["오늘은 작게만…"],
    STACK_LEAD: ["이겼으면 이제 줄여야죠."],
    TILT_ENTER: ["아 진짜 열받네. 아니 참자."],
  },
};

export function linesFor(id: string, trigger: TriggerType): string[] {
  return DIALOGUE[id]?.[trigger] ?? [];
}
